name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build
    - run: rm -rf node_modules
    - uses: actions/checkout@v2
      with:
        repository: 'refinedmods/sitegen'
        path: 'sitegen/'
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - run: cd sitegen
    - run: go build
    - run: chown $USER sitegen
    - run: cd ..
    - run: sudo ./sitegen/sitegen build
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: output/
  deploy:
    - uses: actions/download-artifact@v2
      with:
        name: output
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "output/"
        target: "/home/minecraft/refinedmods/public"
        rm: true
        strip_components: 1