name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build
    - run: rm -rf node_modules
    - uses: actions/upload-artifact@v2
      with:
        name: data
        path: .
  generate-website:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'refinedmods/sitegen'
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - run: go build
    - uses: actions/download-artifact@v2
      with:
        name: data
    - run: chown $USER sitegen
    - run: sitegen -output build/ build