name: CI

on:
  push:
    branches:
      - master

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm run build
    - run: rm -rf node_modules
    - uses: actions/upload-artifact@v2
      with:
        name: frontend-output
        path: .
  build-website:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'refinedmods/sitegen'
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'
    - run: go build
    - uses: actions/download-artifact@v2
      with:
        name: frontend-output
    - run: chown $USER sitegen
    - run: sudo ./sitegen build
    - uses: actions/upload-artifact@v2
      with:
        name: output
        path: output/
  deploy:
    runs-on: ubuntu-latest
    needs: build-website
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: output
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "output/"
        target: "/home/minecraft/refinedmods/public"
        rm: true
        strip_components: 1